name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build a solutions
      run: $buildError = $false; Get-ChildItem -Path . -Include *.sln -Recurse | %{ dotnet build $_.FullName; if( $LASTEXITCODE -ne 0){$buildError=$true}}; if($buildError -eq $true){Write-Host "Error!"; Exit -1}
